# Generated by Django 4.2.8 on 2026-06-10 14:18

from django.db import migrations

def create_admin(apps, schema_editor):
    User = apps.get_model('crud', 'User')
    User.objects.create_superuser(
        username='admin',
        email='admin@celestiarocks.com',
        password='adminpassword',
        role='admin'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_admin),
    ]
