# Generated by Django 4.2.8 on 2026-06-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20260610_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='supplier',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
    ]
