# Generated by Django 4.2.8 on 2026-06-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
