# Generated by Django 4.2.8 on 2026-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_drink_created_at_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('regular', 'Regular Table'), ('vip', 'VIP Booth'), ('bar', 'Bar Seat'), ('lounge', 'Private Lounge')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='seat',
            name='x_coord',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seat',
            name='y_coord',
            field=models.IntegerField(default=0),
        ),
    ]
