# Generated by Django 4.2.8 on 2026-06-10 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_seat_seat_type_seat_x_coord_seat_y_coord'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkproposal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkproposal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='drinkproposal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proposals/'),
        ),
        migrations.AddField(
            model_name='drinkproposal',
            name='manager_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
