# Generated by Django 4.2.8 on 2026-06-11 03:58

from django.db import migrations
from django.utils import timezone
from decimal import Decimal

def seed_data(apps, schema_editor):
    User = apps.get_model('crud', 'User')
    Category = apps.get_model('crud', 'Category')
    Drink = apps.get_model('crud', 'Drink')
    Ingredient = apps.get_model('crud', 'Ingredient')
    Seat = apps.get_model('crud', 'Seat')
    SeatReservation = apps.get_model('crud', 'SeatReservation')
    Order = apps.get_model('crud', 'Order')
    OrderItem = apps.get_model('crud', 'OrderItem')
    CashPayment = apps.get_model('crud', 'CashPayment')

    # Seed Categories
    cat1 = Category.objects.create(name='Cocktails')
    cat2 = Category.objects.create(name='Spirits')

    # Seed Drinks
    d1 = Drink.objects.create(name='Mojito', category=cat1, price=Decimal('250.00'))
    d2 = Drink.objects.create(name='Whiskey Sour', category=cat1, price=Decimal('320.00'))

    # Seed Ingredients
    Ingredient.objects.create(name='Vodka', stock_level=50, low_stock_threshold=10)
    Ingredient.objects.create(name='Lime Juice', stock_level=5, low_stock_threshold=10)

    # Seed Users
    bartender = User.objects.create_user(username='bartender1', role='bartender', password='password123')
    customer = User.objects.create_user(username='customer1', role='customer', password='password123')

    # Seed Seats
    seat = Seat.objects.create(seat_number='VIP-01', is_active=True, seat_type='vip', x_coord=100, y_coord=100)

    # Seed Order
    res = SeatReservation.objects.create(customer=customer, seat=seat, reservation_date=timezone.now().date())
    order = Order.objects.create(customer=customer, seat_reservation=res, total_price=Decimal('570.00'), status='completed')
    OrderItem.objects.create(order=order, drink=d1, quantity=2)
    OrderItem.objects.create(order=order, drink=d2, quantity=1)
    CashPayment.objects.create(order=order, amount=Decimal('570.00'), status='paid')

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_drinkproposal_created_at_drinkproposal_description_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_data),
    ]
