# Generated by Django 4.2.8 on 2026-06-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0009_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
