# Generated by Django 4.2.8 on 2026-06-14 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_drink_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='capacity',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_type',
            field=models.CharField(choices=[('regular', 'Regular Table'), ('vip', 'VIP Booth')], default='regular', max_length=20),
        ),
    ]
